export default function SessionsDocs() {
    return (
        <div className="space-y-6">
            <h1>Session Management</h1>
            <p className="lead">
                Sessions maintain continuity during interaction. They act as the "memory space" for an agent's conversations.
            </p>

            <h2>What is a Session?</h2>
            <p>
                A Session represents a distinct conversational thread. Without sessions, an Agent would have amnesia; it would treat every single message you send as the very first message it has ever received.
            </p>

            <p>
                By binding a conversation to a unique Session ID, PowerDirector ensures that the entire transcript (up to the agent's context window limit) is prepended to subsequent messages, giving the agent seamless short-term memory memory.
            </p>

            <h2>Exploring Sessions</h2>
            <p>
                The <strong>Sessions</strong> view allows administrators to audit past behaviors. Every interaction across all Channels is recorded chronologically.
            </p>

            <h3>Features include:</h3>
            <ul>
                <li><strong>Transcript Inspection</strong>: Read the exact messages sent by the user and the raw responses generated by the agent.</li>
                <li><strong>Token Logging</strong>: See exactly how many tokens were consumed for both the prompt (context) and the completion (response), crucial for auditing API costs.</li>
                <li><strong>Tool Execution Tracking</strong>: Session logs clearly indicate when an agent decided to use a specific Skill (e.g., executing a bash command) and the direct output it received.</li>
            </ul>

            <h2>Context Management</h2>
            <p>
                Sessions automatically prune old messages on an LRU (Least Recently Used) basis if the transcript exceeds the model's configured context window. Advanced users can manually clear a session's history or instruct an Agent to permanently store an important takeaway into its Vector Memory database before the session cycles out.
            </p>

            <h2>Dashboard Sessions</h2>
            <p>
                Note: The <strong>Terminal</strong> channel that you use directly inside this Web UI creates regular Session objects just like any other connection. This represents the primary way developers debug agents locally.
            </p>
        </div>
    );
}
