export const browserCoreExamples = [
  "powerdirector browser status",
  "powerdirector browser start",
  "powerdirector browser stop",
  "powerdirector browser tabs",
  "powerdirector browser open https://example.com",
  "powerdirector browser focus abcd1234",
  "powerdirector browser close abcd1234",
  "powerdirector browser screenshot",
  "powerdirector browser screenshot --full-page",
  "powerdirector browser screenshot --ref 12",
  "powerdirector browser snapshot",
  "powerdirector browser snapshot --format aria --limit 200",
  "powerdirector browser snapshot --efficient",
  "powerdirector browser snapshot --labels",
];

export const browserActionExamples = [
  "powerdirector browser navigate https://example.com",
  "powerdirector browser resize 1280 720",
  "powerdirector browser click 12 --double",
  'powerdirector browser type 23 "hello" --submit',
  "powerdirector browser press Enter",
  "powerdirector browser hover 44",
  "powerdirector browser drag 10 11",
  "powerdirector browser select 9 OptionA OptionB",
  "powerdirector browser upload /tmp/powerdirector/uploads/file.pdf",
  'powerdirector browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "powerdirector browser dialog --accept",
  'powerdirector browser wait --text "Done"',
  "powerdirector browser evaluate --fn '(el) => el.textContent' --ref 7",
  "powerdirector browser console --level error",
  "powerdirector browser pdf",
];
