import type { ChannelMessageActionName as ChannelMessageActionNameFromList } from "./message-action-names";

export { CHANNEL_MESSAGE_ACTION_NAMES } from "./message-action-names";
export { CHANNEL_MESSAGE_CAPABILITIES } from "./message-capabilities";

export type ChannelMessageActionName = ChannelMessageActionNameFromList;
export type { ChannelMessageCapability } from "./message-capabilities";

export type {
  ChannelAuthAdapter,
  ChannelCommandAdapter,
  ChannelCapabilitiesDiagnostics,
  ChannelCapabilitiesDisplayLine,
  ChannelCapabilitiesDisplayTone,
  ChannelConfigAdapter,
  ChannelDirectoryAdapter,
  ChannelExecApprovalAdapter,
  ChannelExecApprovalForwardTarget,
  ChannelExecApprovalInitiatingSurfaceState,
  ChannelResolveKind,
  ChannelResolveResult,
  ChannelResolverAdapter,
  ChannelElevatedAdapter,
  ChannelGatewayAdapter,
  ChannelGatewayContext,
  ChannelGroupAdapter,
  ChannelHeartbeatAdapter,
  ChannelLifecycleAdapter,
  ChannelLoginWithQrStartResult,
  ChannelLoginWithQrWaitResult,
  ChannelLogoutContext,
  ChannelLogoutResult,
  ChannelOutboundAdapter,
  ChannelOutboundContext,
  ChannelAllowlistAdapter,
  ChannelConfiguredBindingConversationRef,
  ChannelConfiguredBindingMatch,
  ChannelConfiguredBindingProvider,
  ChannelPairingAdapter,
  ChannelSecurityAdapter,
  ChannelSetupAdapter,
  ChannelStatusAdapter,
} from "./types.adapters";
export type {
  ChannelAccountSnapshot,
  ChannelAccountState,
  ChannelAgentPromptAdapter,
  ChannelAgentTool,
  ChannelAgentToolFactory,
  ChannelCapabilities,
  ChannelDirectoryEntry,
  ChannelDirectoryEntryKind,
  ChannelGroupContext,
  ChannelHeartbeatDeps,
  ChannelId,
  ChannelLogSink,
  ChannelMentionAdapter,
  ChannelMessageActionAdapter,
  ChannelMessageActionDiscoveryContext,
  ChannelMessageActionContext,
  ChannelMessagingAdapter,
  ChannelMessageToolDiscovery,
  ChannelMeta,
  ChannelMessageToolSchemaContribution,
  ChannelOutboundTargetMode,
  ChannelPollContext,
  ChannelPollResult,
  ChannelSecurityContext,
  ChannelSecurityDmPolicy,
  ChannelSetupInput,
  ChannelStatusIssue,
  ChannelStreamingAdapter,
  ChannelStructuredComponents,
  ChannelThreadingAdapter,
  ChannelThreadingContext,
  ChannelThreadingToolContext,
  ChannelToolSend,
  BaseProbeResult,
  BaseTokenResolution,
} from "./types.core";

export type { ChannelPlugin } from "./types.plugin";
